# Generated by CodeSpeak from spec file: spec.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

from django.db import models


class Player(models.Model):
    """Represents a browser session / player in the Funny Geese game."""
    session_key = models.CharField(max_length=40, unique=True, db_index=True)
    name = models.CharField(max_length=80)   # e.g. "Huggable Alpaca"
    avatar = models.CharField(max_length=10)  # emoji, e.g. "🦙"
    geese_created = models.PositiveIntegerField(default=0)
    geese_popped = models.PositiveIntegerField(default=0)
    last_seen = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-geese_popped', '-geese_created']

    def __str__(self):
        return f"{self.avatar} {self.name}"
