# Generated by CodeSpeak from spec file: spec.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

from django.urls import path
from . import views

app_name = 'geese'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/stats/', views.stats, name='stats'),
    path('api/goose-created/', views.goose_created, name='goose_created'),
    path('api/goose-popped/', views.goose_popped, name='goose_popped'),
]
