# Generated by CodeSpeak from spec file: spec.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

import random

from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET

from .models import Player

# ── Name generation ──────────────────────────────────────────────────────────

ADJECTIVES = [
    "Adorable", "Bouncy", "Cheerful", "Cuddly", "Dapper",
    "Fluffy", "Giggly", "Happy", "Huggable", "Jolly",
    "Lovely", "Merry", "Nimble", "Perky", "Plucky",
    "Quirky", "Rosy", "Snappy", "Spunky", "Sweet",
    "Tiny", "Velvety", "Wiggly", "Zesty", "Bubbly",
]

ANIMALS = [
    ("Alpaca", "🦙"), ("Axolotl", "🦎"), ("Bunny", "🐰"), ("Capybara", "🐾"),
    ("Chinchilla", "🐭"), ("Corgi", "🐕"), ("Duckling", "🐥"), ("Fox", "🦊"),
    ("Hamster", "🐹"), ("Hedgehog", "🦔"), ("Kitten", "🐱"), ("Koala", "🐨"),
    ("Lamb", "🐑"), ("Narwhal", "🦄"), ("Otter", "🦦"), ("Panda", "🐼"),
    ("Penguin", "🐧"), ("Piglet", "🐷"), ("Platypus", "🦆"), ("Puffin", "🐦"),
    ("Quokka", "🦘"), ("Raccoon", "🦝"), ("Sloth", "🦥"), ("Squirrel", "🐿️"),
    ("Wombat", "🐾"),
]


def generate_player_name():
    adj = random.choice(ADJECTIVES)
    animal, emoji = random.choice(ANIMALS)
    return f"{adj} {animal}", emoji


# ── Session → Player helper ──────────────────────────────────────────────────

def get_or_create_player(request):
    """Return (player, created) for the current session."""
    if not request.session.session_key:
        request.session.create()
    key = request.session.session_key
    try:
        player = Player.objects.get(session_key=key)
        return player, False
    except Player.DoesNotExist:
        name, avatar = generate_player_name()
        player = Player.objects.create(
            session_key=key,
            name=name,
            avatar=avatar,
        )
        return player, True


# ── Views ─────────────────────────────────────────────────────────────────────

def index(request):
    player, _ = get_or_create_player(request)
    return render(request, 'geese/index.html', {'player': player})


@require_GET
def stats(request):
    """Return the leaderboard as JSON."""
    players = list(
        Player.objects.values('name', 'avatar', 'geese_created', 'geese_popped')
        .order_by('-geese_popped', '-geese_created')
    )
    return JsonResponse({'players': players})


@csrf_exempt
@require_POST
def goose_created(request):
    """Increment geese_created for the current player."""
    player, _ = get_or_create_player(request)
    Player.objects.filter(pk=player.pk).update(
        geese_created=player.geese_created + 1
    )
    player.refresh_from_db()
    return JsonResponse({'ok': True, 'geese_created': player.geese_created})


@csrf_exempt
@require_POST
def goose_popped(request):
    """Increment geese_popped for the current player."""
    player, _ = get_or_create_player(request)
    Player.objects.filter(pk=player.pk).update(
        geese_popped=player.geese_popped + 1
    )
    player.refresh_from_db()
    return JsonResponse({'ok': True, 'geese_popped': player.geese_popped})
