# Generated by CodeSpeak from spec file: spec.cs.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('geese.urls')),
]
