# Generated by Django 4.2.29 on 2026-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('avatar', models.CharField(max_length=10)),
                ('geese_created', models.PositiveIntegerField(default=0)),
                ('geese_popped', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-geese_popped', '-geese_created'],
            },
        ),
    ]
